site_name: Project Rebirth
nav:
  - Home: index.md
  - 'Lore':
    - 'World': 'world.md'
    - 'Characters':
      - 'Main Character': 'pchar.md'
      - 'The Handler': 'handler.md'
      - 'Other Employees': 'colleagues.md'